#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# start eww daemon
eww daemon &

# Set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.jpg
fi

pidof dunst &> /dev/null
dunstRunning=$?
if [ "$dunstRunning" != "0" ]; then
  dunst &
fi

pidof pipewire &> /dev/null
pipewireRunning=$?
if [ "$pipewireRunning" != "0" ]; then
  pipewire &
  pipewire-pulse &
fi

pidof mpd &> /dev/null
mpdRunning=$?
if [ "$mpdRunning" != "0" ]; then
  mpd ~/.config/mpd/mpd.conf &
fi

pidof picom &> /dev/null
picomRunning=$?
if [ "$picomRunning" != "0" ]; then
  picom --experimental-backends --backend glx --xrender-sync-fence &
fi

pidof udevil &> /dev/null
devmonRunning=$?
if [ "$devmonRunning" != "0" ]; then
  devmon &
fi

setxkbmap latam

#open eww 'bar' windows
#this is a bit of an uggly hack, a more elegant way will hopefully be possible with a future `eww` version

togglebar
